/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme: {
    extend: {
      colors: {
        "surface": "#fff8f3",
        "surface-bright": "#fff8f3",
        "surface-dim": "#e6d8c8",
        "surface-container": "#faecdc",
        "surface-container-low": "#fff2e3",
        "surface-container-high": "#f4e6d6",
        "surface-container-highest": "#eee0d0",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#eee0d0",
        "surface-tint": "#536350",
        "background": "#fff8f3",
        "primary": "#536350",
        "primary-container": "#a8b9a3",
        "primary-fixed": "#d6e8d0",
        "primary-fixed-dim": "#bacbb5",
        "secondary": "#8f4c37",
        "secondary-container": "#ffa98f",
        "secondary-fixed": "#ffdbd0",
        "secondary-fixed-dim": "#ffb59e",
        "tertiary": "#665d52",
        "tertiary-container": "#beb2a5",
        "tertiary-fixed": "#eee0d2",
        "tertiary-fixed-dim": "#d1c5b7",
        "on-surface": "#211b11",
        "on-surface-variant": "#444842",
        "on-background": "#211b11",
        "on-primary": "#ffffff",
        "on-primary-container": "#3b4a39",
        "on-primary-fixed": "#111f10",
        "on-primary-fixed-variant": "#3c4b39",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#7a3b27",
        "on-secondary-fixed": "#3a0b00",
        "on-secondary-fixed-variant": "#723522",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#4d443a",
        "on-tertiary-fixed": "#211b12",
        "on-tertiary-fixed-variant": "#4e453b",
        "outline": "#747871",
        "outline-variant": "#c4c8bf",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "inverse-surface": "#372f25",
        "inverse-on-surface": "#fdefde",
        "inverse-primary": "#bacbb5",
        // Keep old names as aliases for existing components that haven't been migrated
        cream: { DEFAULT: '#FAF6F0', dark: '#F0E9DD' },
        sage: { DEFAULT: '#5B7553', dark: '#3D5435', light: '#8BA583', muted: '#C8D5C2' },
        gold: { DEFAULT: '#C9A84C', light: '#E8D5A0', dark: '#A68A3A' },
        charcoal: '#2A2A2A',
        stone: '#4A4A4A',
        pebble: '#6B6B6B',
        sand: '#D4CFC7',
        cloud: '#F5F2ED',
      },
      fontFamily: {
        headline: ['Noto Serif', 'serif'],
        body: ['Plus Jakarta Sans', 'sans-serif'],
        label: ['Plus Jakarta Sans', 'sans-serif'],
        display: ['Noto Serif', 'Georgia', 'serif'],
        sans: ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
      },
      boxShadow: {
        soft: '0 2px 8px rgba(43,43,43,0.04), 0 1px 2px rgba(43,43,43,0.06)',
        medium: '0 4px 16px rgba(43,43,43,0.06), 0 2px 4px rgba(43,43,43,0.04)',
        large: '0 12px 40px rgba(43,43,43,0.08), 0 4px 12px rgba(43,43,43,0.04)',
        glass: '0 8px 32px rgba(43,43,43,0.08)',
        glow: '0 0 40px rgba(201,168,76,0.15)',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        '2xl': '24px',
        '3xl': '32px',
        full: '9999px',
      },
      backdropBlur: {
        glass: '20px',
      },
    },
  },
  plugins: [
    function ({ addUtilities }) {
      addUtilities({
        '.sr-only': {
          position: 'absolute',
          width: '1px',
          height: '1px',
          padding: '0',
          margin: '-1px',
          overflow: 'hidden',
          clip: 'rect(0, 0, 0, 0)',
          whiteSpace: 'nowrap',
          borderWidth: '0',
        },
        '.focus\\:not-sr-only:focus': {
          position: 'static',
          width: 'auto',
          height: 'auto',
          padding: 'inherit',
          margin: 'inherit',
          overflow: 'visible',
          clip: 'auto',
          whiteSpace: 'normal',
        },
      });
    },
  ],
};
