/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}"],
  theme: {
    extend: {
      colors: {
        primary: "#5a4dc1",
        "on-primary": "#ffffff",
        "primary-container": "#e7deff",
        "on-primary-container": "#000f5e",
        "primary-fixed": "#e7deff",
        "primary-fixed-dim": "#cebdff",
        "on-primary-fixed": "#000f5e",
        "on-primary-fixed-variant": "#3b35a5",
        "inverse-primary": "#cebdff",
        "surface-tint": "#5a4dc1",
        secondary: "#006591",
        "on-secondary": "#ffffff",
        "secondary-container": "#cae6ff",
        "on-secondary-container": "#001e2f",
        "secondary-fixed": "#cae6ff",
        "secondary-fixed-dim": "#8dcdff",
        "on-secondary-fixed": "#001e2f",
        "on-secondary-fixed-variant": "#004c6e",
        tertiary: "#ac2378",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#ffd8eb",
        "on-tertiary-container": "#3e0027",
        "tertiary-fixed": "#ffd8eb",
        "tertiary-fixed-dim": "#ffafd7",
        "on-tertiary-fixed": "#3e0027",
        "on-tertiary-fixed-variant": "#8b005d",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        surface: "#faf8ff",
        "surface-bright": "#faf8ff",
        "surface-dim": "#dbd9e2",
        background: "#faf8ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f2fc",
        "surface-container": "#efecf6",
        "surface-container-high": "#eae7f0",
        "surface-container-highest": "#e4e1ea",
        "on-surface": "#1c1b21",
        "on-background": "#1c1b21",
        "inverse-surface": "#312f36",
        "inverse-on-surface": "#f2eff9",
        "surface-variant": "#e5e0f3",
        "on-surface-variant": "#494454",
        outline: "#797585",
        "outline-variant": "#c9c4d6",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        gutter: "32px",
        "container-max": "1440px",
        "section-gap": "160px",
        unit: "8px",
        "edge-margin": "64px",
      },
      fontFamily: {
        "body-lg": ["DM Sans", "system-ui", "sans-serif"],
        "ui-label": ["Syne", "system-ui", "sans-serif"],
        "display-lg": ["Playfair Display", "Georgia", "serif"],
        "body-md": ["DM Sans", "system-ui", "sans-serif"],
        "headline-lg": ["Playfair Display", "Georgia", "serif"],
        "display-xl": ["Playfair Display", "Georgia", "serif"],
        "headline-lg-mobile": ["Playfair Display", "Georgia", "serif"],
      },
      fontSize: {
        "body-lg": ["20px", { lineHeight: "160%", fontWeight: "400" }],
        "ui-label": [
          "12px",
          { lineHeight: "100%", letterSpacing: "0.15em", fontWeight: "700" },
        ],
        "display-lg": [
          "80px",
          { lineHeight: "110%", letterSpacing: "-0.01em", fontWeight: "400" },
        ],
        "body-md": ["16px", { lineHeight: "160%", fontWeight: "400" }],
        "headline-lg": ["48px", { lineHeight: "120%", fontWeight: "400" }],
        "display-xl": [
          "120px",
          { lineHeight: "110%", letterSpacing: "-0.02em", fontWeight: "400" },
        ],
        "headline-lg-mobile": [
          "32px",
          { lineHeight: "120%", fontWeight: "400" },
        ],
      },
    },
  },
  plugins: [],
};
